CREATE DATABASE HackMTY2017;

USE HackMTY2017;

CREATE TABLE Usuario(
	ID INT NOT NULL AUTO_INCREMENT,
	Name VARCHAR(30) NOT NULL,
	Email VARCHAR(254) NOT NULL,
	LinkedID VARCHAR(256),
	Github VARCHAR(256),
	Photo BLOB,
	PRIMARY KEY (ID)
);

CREATE TABLE Project(
	ID INT NOT NULL AUTO_INCREMENT,
	Status VARCHAR(15) NOT NULL,
	Name VARCHAR(30) NOT NULL,
	Description VARCHAR(280) NOT NULL,
	ShortDescription VARCHAR(140) NOT NULL,
	Photo BLOB,
	OwnerUser INT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (OwnerUser) REFERENCES Usuario (ID)
);

CREATE TABLE Skill(
	ID INT NOT NULL AUTO_INCREMENT,
	Name VARCHAR(30) NOT NULL,
	Hex VARCHAR(6) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE Role(
	ID INT NOT NULL AUTO_INCREMENT,
	Name VARCHAR(30) NOT NULL,
	Hex VARCHAR(6) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE ProjectSkill(
	ProjectID INT NOT NULL,
	SkillID INT NOT NULL,
	PRIMARY KEY (ProjectID, SkillID),
	FOREIGN KEY (ProjectID) REFERENCES Project (ID),
	FOREIGN KEY (SkillID) REFERENCES Skill (ID)
);

CREATE TABLE ProjectRole(
	ProjectID INT NOT NULL,
	RoleID INT NOT NULL,
	PRIMARY KEY (ProjectID, RoleID),
	FOREIGN KEY (ProjectID) REFERENCES Project (ID),
	FOREIGN KEY (RoleID) REFERENCES Role (ID)
);

CREATE TABLE Enroll(
	ProjectID INT NOT NULL,
	UserID INT NOT NULL,
	PRIMARY KEY (ProjectID, UserID),
	FOREIGN KEY (ProjectID) REFERENCES Project (ID),
	FOREIGN KEY (UserID) REFERENCES Usuario (ID)
);

CREATE TABLE Request(
	ProjectID INT NOT NULL,
	UserID INT NOT NULL,
	RequestDate DATETIME NOT NULL,
	PRIMARY KEY (ProjectID, UserID),
	FOREIGN KEY (ProjectID) REFERENCES Project (ID),
	FOREIGN KEY (UserID) REFERENCES Usuario (ID)
);

CREATE TABLE UserRole(
	UserID INT,
	RoleID INT,
	PRIMARY KEY (UserID, RoleID),
	FOREIGN KEY (UserID) REFERENCES Usuario (ID),
	FOREIGN KEY (RoleID) REFERENCES Role (ID)
);

CREATE TABLE UserSkill(
	UserID INT,
	SkillID INT,
	PRIMARY KEY (UserID, SkillID),
	FOREIGN KEY (UserID) REFERENCES Usuario (ID),
	FOREIGN KEY (SkillID) REFERENCES Skill (ID)
);

